<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net9.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup><ItemGroup><ProjectReference Include="../BCIT615.Assessment1.GamePlayer.Contracts/BCIT615.Assessment1.GamePlayer.Contracts.csproj" /></ItemGroup></Project>
